#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend nimasolutions.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 526506-web-01 18.206.198.212
        server 526506-web-02 100.26.153.160
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
